PowerBlog.Site/Models/Order.cs
using System.ComponentModel.DataAnnotations;
namespace PowerBlog.Site.Models
{
    public class Order
    {
        [Key]
        public long Id { get; set; }
        public DateTime? OrderDate { get; set; } = DateTime.Now;
        public DateTime? PayDate { get; set; }
        public PaymentStatus PaymentStatus { get; set; }
        public string? TransactionId { get; set; }

        #region Relations
        public User? User { get; set; }
        public long? UserId { get; set; }
        public Blog? Blog { get; set; }
        public long? BlogId { get; set; }
        public OfferPay? OfferPay { get; set; }
        public long? OfferPayId { get; set; }
        #endregion
    }
}

PowerBlog.Site/Controllers/OfferController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PowerBlog.Site.Attributes;
using PowerBlog.Site.Data;

namespace PowerBlog.Site.Controllers
{
    [IsLoggedIn]
    public class OfferController : Controller
    {
        private readonly ApplicationDbContext _context;
        public OfferController(ApplicationDbContext context)
        {
            _context = context;
        }
        [HttpPost]
        public async Task<IActionResult> CalculationOffer(string? offerWord, decimal? amount)
        {
            decimal? offerAmount = 0;
            if (offerWord == null)
            {
                TempData["ErrorMessage"] = "کد تخفیف وارد شده صحیح نمی باشد.";
                return RedirectToAction("Index", "Order");
            }
            var offer = await _context.OfferPays.FirstOrDefaultAsync(o => o.OfferWord == offerWord);
            if (offer == null || offer.IsDisable == true)
            {
                TempData["ErrorMessage"] = "کد تخفیف وارد شده صحیح نمی باشد.";
                return RedirectToAction("Index", "Order");
            }
            if (offer.OfferPercentage != null)
            {
                offerAmount = amount - (amount * offer.OfferPercentage / 100);
            }
            else if (offer.OfferAmount != null)
            {
                offerAmount = amount - offer.OfferAmount;
                if (offerAmount < 0)
                {
                    offerAmount = 0;
                }
            }
            TempData["OfferAmount"] = offerAmount.ToString();
            TempData["OfferWord"] = offer.Id.ToString();
            return RedirectToAction("Index", "Order");
        }
        public IActionResult DeleteOffer()
        {
            TempData.Remove("OfferAmount");
            return RedirectToAction("Index", "Order");
        }
    }
}

PowerBlog.Site/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using PowerBlog.Site.Attributes;
using PowerBlog.Site.Data;
using PowerBlog.Site.Models;

namespace PowerBlog.Site.Controllers
{
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _context;
        public OrderController(ApplicationDbContext context)
        {
            _context = context;
        }
        [IsLoggedIn]
        public async Task<IActionResult> Index()
        {
            var userId = long.Parse(HttpContext.Session.GetString("UserId")!);
            var orders = await _context.Orders.Include(o => o.Blog).ThenInclude(b => b!.Category).Include(o => o.Blog).ThenInclude(b => b!.User).Where(o => o.UserId == userId && o.PaymentStatus == PaymentStatus.Pending).ToListAsync();
            return View(orders);
        }
        [HttpPost]
        public async Task<IActionResult> PostAddNewOrder(Order order, long? blogId)
        {
            var userId = HttpContext.Session.GetString("UserId");
            if (userId == null)
            {
                TempData["ErrorMessageAddToOrder"] = "برای اضافه کردن مقاله به سبد خرید باید ابتدا وارد سایت شوید.";
                return RedirectToAction("Details", "PriceBlog", new { id = order.BlogId });
            }
            order.UserId = long.Parse(userId);
            order.PaymentStatus = PaymentStatus.Pending;
            await _context.Orders.AddAsync(order);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "PriceBlog", new { id = blogId });
        }
        [HttpPost]
        public async Task<IActionResult> PostDeleteOrder(long? orderId)
        {
            if (orderId == null)
            {
                return NotFound();
            }
            var order = await _context.Orders.FirstOrDefaultAsync(o => o.Id == orderId);
            if (order == null)
            {
                return NotFound();
            }
            var blogId = order.BlogId;
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "PriceBlog", new { id = blogId });
        }
        [HttpPost]
        public async Task<IActionResult> PostPay(decimal? amount)
        {
            if (amount == null)
            {
                return NotFound();
            }
            amount = amount * 10;
            var client = new HttpClient();
            var request = new HttpRequestMessage(HttpMethod.Post, "https://gateway.zibal.ir/v1/request");
            var content = new StringContent("{\r\n    \"merchant\":\"zibal\",\r\n    \"amount\": " + amount + ",\r\n    \"callbackUrl\":\"https://localhost:44306/Order/GetPayStatus\"\r\n}", null, "application/json");
            request.Content = content;
            var response = await client.SendAsync(request);
            response.EnsureSuccessStatusCode();
            var result = await response.Content.ReadAsStringAsync();
            var jsonObj = JObject.Parse(result);
            var trackId = jsonObj["trackId"]?.ToString();
            return Redirect($"https://gateway.zibal.ir/start/{trackId}");
        }
        public async Task<IActionResult> GetPayStatus(string success, string status, string trackId)
        {
            if (int.Parse(success) != 1 || (int.Parse(status) != 1 && int.Parse(status) != 2))
            {
                TempData["ErrorMessage"] = "پرداخت ناموفق بود.";
                return RedirectToAction("Index", "Order");
            }
            var userId = long.Parse(HttpContext.Session.GetString("UserId")!);
            var orders = await _context.Orders.Where(o => o.PaymentStatus == PaymentStatus.Pending && o.UserId == userId).ToListAsync();
            foreach (var order in orders)
            {
                order.PaymentStatus = PaymentStatus.Paid;
                order.TransactionId = trackId;
                order.PayDate = DateTime.Now;
                if (TempData["OfferWord"] != null)
                {
                    order.OfferPayId = long.Parse(TempData["OfferWord"]?.ToString()!);
                    TempData.Keep("OfferWord");
                }
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Order");
        }
        //public async Task<IActionResult> SidebarOrder()
        //{
        //    var userIdString = HttpContext.Session.GetString("UserId");
        //    if (userIdString == null)
        //    {
        //        return NotFound();
        //    }
        //    var userId = long.Parse(userIdString);
        //    var orders = await _context.Orders.Where(o => o.PaymentStatus == PaymentStatus.Pending && o.UserId == userId).ToListAsync();
        //    return Ok(orders);
        //}
    }
}

PowerBlog.Site/Views/Order/Index.cshtml
@model IEnumerable<Order>
@{
    var counter = 1;
}
@if (TempData["ErrorMessage"] != null)
{
    <h2 class="font-MorabbaMedium text-lg lg:text-2xl">
        @TempData["ErrorMessage"]
    </h2>
    TempData.Remove("ErrorMessage");
}
@if (Model.Count() == 0)
{
    <div class="relative mt-4 overflow-x-auto shadow rounded-lg">
        <table class="justify-center w-full text-sm text-right text-gray-500 dark:text-gray-400">
            <thead class="justify-center text-xs text-gray-700 bg-gray-50 dark:bg-zinc-700 dark:text-gray-200">
                <tr>
                    <th scope="col" class="px-6 py-3.5">پیام</th>
                </tr>
            </thead>
            <tbody>
                <tr class="justify-center bg-white border-b dark:bg-zinc-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-zinc-600">
                    <td class="px-6 py-5">هیچ محصولی به سبد خرید اضافه نکردید</td>
                </tr>
            </tbody>
        </table>
    </div>
}
else
{
    <div class="relative mt-4 overflow-x-auto shadow rounded-lg">
        <table class="justify-center w-full text-sm text-right text-gray-500 dark:text-gray-400">
            <thead class="justify-center text-xs text-gray-700 bg-gray-50 dark:bg-zinc-700 dark:text-gray-200">
                <tr>
                    <th scope="col" class="px-6 py-3.5">#</th>
                    <th scope="col" class="px-6 py-3.5">عنوان</th>
                    <th scope="col" class="px-6 py-3.5">دسته بندی</th>
                    <th scope="col" class="px-6 py-3.5">نویسنده</th>
                    <th scope="col" class="px-6 py-3.5">قیمت</th>
                    <th scope="col" class="px-6 py-3.5">عملیات</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="justify-center bg-white border-b dark:bg-zinc-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-zinc-600">
                        <td class="px-6 py-5">@counter</td>
                        <th scope="row" class="px-6 py-5 font-medium text-gray-900 whitespace-nowrap dark:text-white">@item?.Blog?.Title</th>
                        <td class="px-6 py-5">@item?.Blog?.Category?.Name</td>
                        <td class="px-6 py-5">@(item?.Blog?.User?.FirstName+" "+item?.Blog?.User?.LastName)</td>
                        <td class="px-6 py-5">@item?.Blog?.Price?.ToString("N0") تومان</td>
                        <td class="px-6 py-5 text-red-500">
                            <form asp-action="PostDeleteOrder" asp-controller="Order" asp-area="" asp-route-orderId="@item?.Id" method="post">
                                <button class="w-full flex items-center gap-x-1 justify-center bg-red-500 text-white hover:bg-red-600 transition-all rounded-lg shadow py-2">حذف</button>
                            </form>
                        </td>
                    </tr>
                    counter++;
                }
                <tr class="justify-center bg-white border-b dark:bg-zinc-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-zinc-600">
                    <td class="px-6 py-5"></td>
                    <th scope="row" class="px-6 py-5 font-medium text-gray-900 whitespace-nowrap dark:text-white"></th>
                    <td class="px-6 py-5"></td>
                    <td class="px-6 py-5"></td>
                    @if (TempData["OfferAmount"] != null)
                    {
                        <td class="px-6 py-5">مجموع: @Model.Sum(o => o.Blog?.Price)?.ToString("N0") تومان با تخفیف @((decimal.TryParse(TempData["OfferAmount"]?.ToString(), out var amount) ? amount.ToString("N0") : "0")) تومان</td>
                    }
                    else
                    {
                        <td class="px-6 py-5">مجموع: @Model.Sum(o => o.Blog?.Price)?.ToString("N0") تومان</td>
                    }
                    <td class="px-6 py-5 text-red-500"></td>
                </tr>
            </tbody>
        </table>
        @if (TempData["OfferAmount"] == null)
        {
            <form asp-action="CalculationOffer" asp-controller="Offer" asp-area="" asp-route-amount="@Model.Sum(o => o.Blog?.Price)" method="post">
                <h2 class="font-MorabbaMedium text-lg lg:text-2xl">
                    کد تخفیف دارید؟ وارد کنید:
                </h2>
                <input style="color:black;" type="text" name="offerWord" id="offerWord" />
                <button id="offerBtn" class="flex items-center gap-x-1 justify-center bg-violet-500 text-white hover:bg-violet-600 transition-all rounded-lg shadow py-2">اعمال کد تخفیف</button>
            </form>
        }
        else
        {
            <a asp-action="DeleteOffer" asp-controller="Offer" asp-area="" id="offerBtn" class="flex items-center gap-x-1 justify-center bg-rose-500 text-white hover:bg-rose-600 transition-all rounded-lg shadow py-2">حذف کد تخفیف</a>
        }
        @if (TempData["OfferAmount"] != null)
        {
            <form asp-action="PostPay" asp-controller="Order" asp-area="" asp-route-amount="@TempData["OfferAmount"]" method="post">
                <button class="w-full flex items-center gap-x-1 justify-center bg-green-500 text-white hover:bg-green-600 transition-all rounded-lg shadow py-2">پرداخت</button>
            </form>
            <form asp-action="PostBuyBlog" asp-controller="Wallet" asp-area="" asp-route-amount="@TempData["OfferAmount"]" method="post">
                <button class="w-full flex items-center gap-x-1 justify-center bg-rose-500 text-white hover:bg-rose-600 transition-all rounded-lg shadow py-2">پرداخت با کیف پول</button>
            </form>
            TempData.Remove("OfferAmount");
        }
        else
        {
            <form asp-action="PostPay" asp-controller="Order" asp-area="" asp-route-amount="@Model.Sum(o => o.Blog?.Price)" method="post">
                <button class="w-full flex items-center gap-x-1 justify-center bg-green-500 text-white hover:bg-green-600 transition-all rounded-lg shadow py-2">پرداخت</button>
            </form>
            <form asp-action="PostBuyBlog" asp-controller="Wallet" asp-area="" asp-route-amount="@Model.Sum(o => o.Blog?.Price)" method="post">
                <button class="w-full flex items-center gap-x-1 justify-center bg-rose-500 text-white hover:bg-rose-600 transition-all rounded-lg shadow py-2">پرداخت با کیف پول</button>
            </form>
        }
    </div>
}