PowerBlog.Site/Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PowerBlog.Site.Attributes;
using PowerBlog.Site.Data;
using PowerBlog.Site.Models;

namespace PowerBlog.Site.Controllers
{
    public class CommentController : Controller
    {
        private readonly ApplicationDbContext _context;
        public CommentController(ApplicationDbContext context)
        {
            _context = context;
        }
        [HttpPost]
        public async Task<IActionResult> PostComment(Comment comment)
        {
            var user = HttpContext.Session.GetString("UserId");
            var blog = await _context.Blogs.FirstOrDefaultAsync(b => b.Id == comment.BlogId);
            if (user == null)
            {
                TempData["ErrorMessage"] = "برای ارسال نظر ابتدا وارد حساب کاربری خود شوید";
                if (blog?.Price != null)
                {
                    return RedirectToAction("Details", "PriceBlog", new { id = comment.BlogId });
                }
                return RedirectToAction("Details", "Blog", new { id = comment.BlogId });
            }
            comment.CreateDate = DateTime.Now;
            comment.UserId = long.Parse(user);
            await _context.Comments.AddAsync(comment);
            await _context.SaveChangesAsync();
            if (blog?.Price != null)
            {
                return RedirectToAction("Details", "PriceBlog", new { id = comment.BlogId });
            }
            return RedirectToAction("Details", "Blog", new { id = comment.BlogId });
        }
    }
}

PowerBlog.Site/Controllers/UserCommentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PowerBlog.Site.Attributes;
using PowerBlog.Site.Data;

namespace PowerBlog.Site.Controllers
{
    [IsLoggedIn]
    public class UserCommentController : Controller
    {
        private readonly ApplicationDbContext _context;
        public UserCommentController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var userId = long.Parse(HttpContext.Session.GetString("UserId")!);
            var comments = await _context.Comments.Include(c => c.Blog).Where(c => c.UserId == userId).ToListAsync();
            return View(comments);
        }
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var comment = await _context.Comments.Include(c => c.Blog).FirstOrDefaultAsync(c => c.Id == id);
            if (comment == null)
            {
                return NotFound();
            }
            return View(comment);
        }
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var comment = await _context.Comments.FirstOrDefaultAsync(c => c.Id == id);
            if (comment == null)
            {
                return NotFound();
            }
            _context.Comments.Remove(comment);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "UserComment", new { area = "" });
        }
    }
}

PowerBlog.Site/Views/UserComment/Details.cshtml
@model Comment
@{
    Layout = "_UserPanelLayout";
}
<div class="row gx-3">
    <div class="col-sm-12">
        <div class="card mb-3">
            <div class="card-header">
                <h5 class="card-title">مشاهده جزئیات</h5>
            </div>
            <div class="card-body">
                <!-- Row starts -->
                <div class="row gx-3">
                    <div class="col-lg-3 col-sm-4 col-12">
                        <div class="mb-3">
                            <label class="form-label" asp-for="@Model.Title">عنوان</label>
                            <input type="text" class="form-control" asp-for="@Model.Title" value="@Model.Title" readonly>
                        </div>
                    </div>
                    <div class="col-sm-12 col-12">
                        <div class="mb-3">
                            <label class="form-label" asp-for="@Model.TextBody">متن کامنت</label>
                            <textarea class="form-control" asp-for="@Model.TextBody" value="@Model.TextBody" readonly rows="3"></textarea>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-4 col-12">
                        <div class="mb-3">
                            <label class="form-label" asp-for="@Model!.Blog!.Title">مقاله</label>
                            <input type="text" class="form-control" asp-for="@Model!.Blog!.Title" value="@Model?.Blog?.Title" readonly>
                        </div>
                    </div>
                    <div class="form-check">
                        @if (Model!.IsConfirmation)
                        {
                            <input class="form-check-input" type="checkbox" asp-for="@Model.IsConfirmation" checked="checked" disabled>
                        }
                        else
                        {
                            <input class="form-check-input" type="checkbox" asp-for="@Model.IsConfirmation" disabled>
                        }
                        <label class="form-check-label" asp-for="@Model.IsConfirmation">وضعیت تایید</label>
                    </div>
                </div>
                <!-- Row ends -->
            </div>
            @*<div class="card-footer">
                    <div class="d-flex gap-2 justify-content-end">
                        <a asp-action="Edit" asp-controller="Comment" asp-area="Admin" asp-route-id="@Model.Id" class="btn btn-outline-info">ویرایش</a>
                    </div>
                </div>*@
        </div>
    </div>
</div>

PowerBlog.Site/Views/UserComment/Index.cshtml
@using PowerBlog.Site.Utilities
@model IEnumerable<Comment>
@{
    Layout = "_UserPanelLayout";
    int counter = 1;
}
<div class="table-responsive">
    <div class="table-outer">
        <table class="table table-striped m-0">
            <thead>
                <tr>
                    <th>#</th>
                    <th>عنوان</th>
                    <th>مقاله</th>
                    <th>تاریخ ایجاد</th>
                    <th>وضعیت تایید</th>
                    <th>عملیات</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@counter</td>
                        <td>@item.Title</td>
                        <td>@item?.Blog?.Title</td>
                        <td>@item?.CreateDate!.Value.ToShamsi()</td>
                        <td>@(item!.IsConfirmation?"تایید شده":"تایید نشده")</td>
                        <td>
                            <a asp-action="Details" asp-controller="UserComment" asp-area="" asp-route-id="@item.Id" class="btn btn-outline-info">جزئیات</a> <a asp-action="Delete" asp-controller="UserComment" asp-area="" asp-route-id="@item.Id" class="btn btn-outline-danger">حذف</a>
                        </td>
                    </tr>
                    counter++;
                }
            </tbody>
        </table>
    </div>
</div>