PowerBlog.Site/Controllers/PriceBlogController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PowerBlog.Site.Data;
using PowerBlog.Site.Models;
using PowerBlog.Site.Models.ViewModels;

namespace PowerBlog.Site.Controllers
{
    public class PriceBlogController : Controller
    {
        private readonly ApplicationDbContext _context;
        public PriceBlogController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var priceBlogs = await _context.Blogs.Where(b => b.IsPublish == true && b.Price != null).ToListAsync();
            return View(priceBlogs);
        }
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var blog = await _context.Blogs.Include(b => b.Comments!.Where(c => c.IsConfirmation == true)).ThenInclude(c => c.User).Include(b => b.Comments!.Where(c => c.IsConfirmation == true)).ThenInclude(c => c.ReactionBlogs).Include(b => b.User).Include(b => b.ReactionBlogs).FirstOrDefaultAsync(b => b.Id == id && b.IsPublish == true && b.Price != null);
            if (blog == null)
            {
                return NotFound();
            }
            blog.View++;
            await _context.SaveChangesAsync();

            var ctegories = await _context.Categories.OrderByDescending(c => c.CreateDate).Take(5).ToListAsync();

            var recentBlogs = await _context.Blogs.Where(b => b.Price != null && b.Id != id&&b.IsPublish==true).OrderByDescending(b => b.CreateDate).Take(5).ToListAsync();


            var userId = HttpContext.Session.GetString("UserId");
            bool isUserAddToFavorite = false;
            bool isUserAddToOrder = false;
            if (userId != null)
            {
                isUserAddToFavorite = await _context.Favorites.AnyAsync(f => f.BlogId == blog.Id && f.UserId == long.Parse(userId));
                var favorite = await _context.Favorites.FirstOrDefaultAsync(f => f.BlogId == blog.Id && f.UserId == long.Parse(userId));
                TempData["FavoriteId"] = favorite?.Id;
                isUserAddToOrder = await _context.Orders.AnyAsync(o => o.BlogId == blog.Id && o.UserId == long.Parse(userId) && o.PaymentStatus == PaymentStatus.Pending);
                var order = await _context.Orders.Include(o => o.User).Include(o => o.Blog).FirstOrDefaultAsync(o => o.BlogId == blog.Id && o.UserId == long.Parse(userId));
                if (order?.PaymentStatus == PaymentStatus.Paid)
                {
                    TempData["IsPaid"] = true;
                }
                else
                {
                    TempData["IsPaid"] = false;
                    TempData["OrderId"] = order?.Id;
                }
            }
            if (userId == null || isUserAddToFavorite == false)
            {
                TempData["IsUserAddToFavoritePrice"] = false;
            }
            else
            {
                TempData["IsUserAddToFavoritePrice"] = true;
            }
            if (userId == null || isUserAddToOrder == false)
            {
                TempData["IsUserAddToOrderPrice"] = false;
            }
            else
            {
                TempData["IsUserAddToOrderPrice"] = true;
            }
            var blogViewModel = new BlogViewModel()
            {
                Blog = blog,
                Categories = ctegories,
                RecentBlogs = recentBlogs
            };
            return View(blogViewModel);
        }
    }
}

PowerBlog.Site/Views/PriceBlog/Index.cshtml
@using PowerBlog.Site.Utilities
@model IEnumerable<Blog>
<main class="container child:mt-8">
    <section>
        <ul class="flex items-center gap-x-2 text-gray-400 text-sm lg:text-base">
            <li class="flex items-center gap-x-2">
                <a asp-action="Index" asp-controller="Home" asp-area="">صفحه اصلی</a>
                <svg class="w-4 h-4"><use href="#chevron-left"></use></svg>
            </li>
            <li class="flex items-center gap-x-2"><a asp-action="Index" asp-controller="PriceBlog" asp-area="">فروشگاه</a></li>
        </ul>
    </section>
    <div class="flex flex-col lg:flex-row gap-4">
        <div class="lg:sticky top-1 h-fit lg:w-1/4 flex flex-col gap-y-4 items-center shadow rounded-lg p-4 dark:bg-zinc-700 bg-white">
            <div class="flex items-center justify-between w-full">
                <span class="flex items-center gap-x-1">
                    <svg class="w-5 h-5"><use href="#filter"></use></svg>
                    <p class="font-DanaMedium">فیلتر ها</p>
                </span>
                <p class="text-green-500">حدف همه</p>
            </div>
            <div class="mt-3 w-full dark:bg-zinc-600 cursor-pointer shadow rounded-lg">
                <div class="accordion-header p-3 flex items-center justify-between">
                    <p class="font-DanaMedium">دسته بندی</p>
                    <svg class="w-4 h-4"><use href="#chevron-left"></use></svg>
                </div>
                <ul class="accordion-content hidden py-2 mx-2 child:dark:text-gray-200 child:text-gray-600 child:flex items-center child:gap-x-2 child:py-1 child:px-2 child:rounded space-y-2">
                    <li>
                        <label class="cl-checkbox">
                            <input checked="" type="checkbox" /> <span></span>
                        </label>
                        <p>کپسول قهوه</p>
                    </li>
                    <li>
                        <label class="cl-checkbox">
                            <input type="checkbox" /> <span></span>
                        </label>
                        <p>دانه قهوه</p>
                    </li>
                    <li>
                        <label class="cl-checkbox">
                            <input type="checkbox" /> <span></span>
                        </label>
                        <p>قهوه ساز</p>
                    </li>
                </ul>
            </div>
            <div class="w-full dark:bg-zinc-600 cursor-pointer shadow rounded-lg">
                <div class="accordion-header p-3 flex items-center justify-between">
                    <p class="font-DanaMedium">برند</p>
                    <svg class="w-4 h-4"><use href="#chevron-left"></use></svg>
                </div>
                <ul class="accordion-content hidden mx-2 py-2 child:dark:text-gray-200 child:text-gray-600 child:flex items-center child:gap-x-2 child:py-1 child:px-2 child:rounded space-y-2">
                    <li>
                        <label class="cl-checkbox">
                            <input type="checkbox" /> <span></span>
                        </label>
                        <p>بن مانو</p>
                    </li>
                    <li>
                        <label class="cl-checkbox">
                            <input type="checkbox" /> <span></span>
                        </label>
                        <p>اسپرسو</p>
                    </li>
                </ul>
            </div>
            <div class="w-full dark:bg-zinc-600 cursor-pointer shadow rounded-lg">
                <div class="accordion-header p-3 flex items-center justify-between">
                    <p class="font-DanaMedium">میزان کافئین</p>
                    <svg class="w-4 h-4"><use href="#chevron-left"></use></svg>
                </div>
                <ul class="accordion-content hidden py-2 mx-2 child:dark:text-gray-200 child:text-gray-600 child:flex items-center child:gap-x-2 child:py-1 child:px-2 child:rounded space-y-2">
                    <li>
                        <label class="cl-checkbox">
                            <input checked="" type="checkbox" /> <span></span>
                        </label>
                        <p>بالا</p>
                    </li>
                    <li>
                        <label class="cl-checkbox">
                            <input type="checkbox" /> <span></span>
                        </label>
                        <p>متوسط</p>
                    </li>
                    <li>
                        <label class="cl-checkbox">
                            <input type="checkbox" /> <span></span>
                        </label>
                        <p>کم</p>
                    </li>
                </ul>
            </div>
            <div class="wrapper my-4">
                <div class="slider-bar">
                    <div class="progress" style="left: 0%; right: 37.122%"></div>
                </div>
                <div class="range-input">
                    <input type="range"
                           min="0"
                           max="100000"
                           value="0"
                           class="min-range" />
                    <input type="range"
                           min="0"
                           max="100000"
                           value="35000"
                           class="max-range" />
                </div>
                <div class="price-input mt-3 text-green-600">
                    <div class="field justify-start">
                        <span class="text-sm font-DanaMedium mr-2">تومان</span>
                        <p class="min-input">0</p>
                    </div>
                    <div class="field justify-end">
                        <span class="text-sm font-DanaMedium mr-2">تومان</span>
                        <p class="max-input">628,780</p>
                    </div>
                </div>
            </div>
            <div class="flex my-2 w-full flex-col h-auto gap-y-5 child:flex child:items-center child:justify-between child:font-DanaMedium">
                <div class="">
                    <p>فقط کالا های موجود</p>
                    <label class="switch">
                        <input type="checkbox" /> <span class="slider"></span>
                    </label>
                </div>
                <div class="">
                    <p>فقط محصولات ویژه</p>
                    <label class="switch">
                        <input type="checkbox" /> <span class="slider"></span>
                    </label>
                </div>
            </div>
        </div>
        <div class="lg:w-3/4">
            <div class="dark:bg-zinc-700 bg-white flex flex-wrap items-center justify-start lg:gap-x-8 py-2 px-2 sm:px-4 shadow rounded-lg sm:h-16">
                <div class="flex items-center gap-x-2">
                    <svg class="w-5 h-5"><use href="#sort-list"></use></svg>
                    <h2 class="font-DanaDemiBold">مرتب سازی بر اساس :</h2>
                </div>
                <ul class="flex items-center gap-x-1 lg:gap-x-5 child:transition-all child:cursor-pointer child-hover:bg-gray-300/30 child:rounded-lg child:px-1 child:py-1 child:text-sm child:lg:text-base">
                    <li class="text-green-500">محبوب ترین</li>
                    <li>پرفروش ترین</li>
                    <li>ارزان ترین</li>
                    <li>گران ترین</li>
                </ul>
            </div>
            <div class="mt-4 grid grid-cols-2 sm:grid-cols-3 xl:grid-cols-4 gap-3 xs:gap-6 sm:gap-7 child:cursor-pointer child:overflow-hidden child:rounded-lg child:bg-white child:dark:bg-zinc-700 child:shadow lg:child:w-56 child:relative">
                @foreach (var item in Model)
                {
                    <div class="group">
                        <a asp-action="Details" asp-controller="PriceBlog" asp-route-id="@item.Id" asp-area="" class="line-clamp-2 font-DanaMedium mb-2 text-sm lg:text-base">
                            <img src="~/Images/BlogImages/@item.Photo"
                                 alt="@item.Title"
                                 class="group-hover:scale-105 duration-300 w-32 h-32 lg:w-48 lg:h-48 mx-auto mb-3" />
                            <div class="px-2 lg:px-4 mb-3">
                                @item.Title
                                <div class="flex items-center gap-x-1 lg:gap-x-3">
                                    <p class="font-DanaDemiBold text-green-600 dark:text-green-500">
                                        @item.Price?.ToString("N0") <span class="font-Dana text-sm">تومان</span>
                                    </p>
                                </div>
                            </div>
                        </a>
                        <div class="flex items-center justify-between px-2 lg:px-4 mb-3">
                            <div class="flex items-center gap-x-2 child:transition-all child:duration-300">
                                <span class="rounded-full p-2 dark:bg-zinc-800 dark:hover:bg-green-500 bg-gray-100 hover:bg-green-600 hover:text-white">
                                    <svg class="w-4 h-4">
                                        <use href="#shopping-cart"></use>
                                    </svg>
                                </span>
                                @*<span class="hover:text-green-600">
                                        <svg class="w-4 h-4">
                                            <use href="#heart"></use>
                                        </svg>
                                    </span>*@
                            </div>
                            @*<div class="flex items-center">
                                    <svg class="w-4 h-4 text-gray-300"><use href="#star"></use></svg>
                                    <svg class="w-4 h-4 text-yellow-400">
                                        <use href="#star"></use>
                                    </svg>
                                    <svg class="w-4 h-4 text-yellow-400">
                                        <use href="#star"></use>
                                    </svg>
                                    <svg class="w-4 h-4 text-yellow-400">
                                        <use href="#star"></use>
                                    </svg>
                                    <svg class="w-4 h-4 text-yellow-400">
                                        <use href="#star"></use>
                                    </svg>
                                </div>*@
                        </div>
                    </div>
                }
            </div>
            <div class="mt-10 w-full flex items-center justify-center">
                <ul class="flex items-center gap-x-3 child:flex child:items-center child:justify-center child:w-8 child:h-8 child:cursor-pointer child:shadow child:rounded-lg child:transition-all child:duration-300">
                    <li class="bg-white dark:bg-zinc-700 hover:bg-green-500 hover:text-white">
                        <svg class="w-5 h-5"><use href="#chevron-right"></use></svg>
                    </li>
                    <li class="text-white bg-green-500"><a href="#">1</a></li>
                    <li class="bg-white dark:bg-zinc-700 hover:bg-green-500 hover:text-white">
                        <a href="#">2</a>
                    </li>
                    <li class="bg-white dark:bg-zinc-700 hover:bg-green-500 hover:text-white">
                        <a href="#">...</a>
                    </li>
                    <li class="bg-white dark:bg-zinc-700 hover:bg-green-500 hover:text-white">
                        <svg class="w-5 h-5"><use href="#chevron-left"></use></svg>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</main>