PowerBlog.Site/Areas/Admin/Controllers/UserManagerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PowerBlog.Site.Attributes;
using PowerBlog.Site.Data;
using PowerBlog.Site.Models;
using PowerBlog.Site.Utilities;

namespace PowerBlog.Site.Areas.Admin.Controllers
{
    [Area("Admin")]
    [AdminAuthorize]
    public class UserManagerController : Controller
    {
        private readonly ApplicationDbContext _context;
        public UserManagerController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var users = await _context.Users.OrderByDescending(u => u.UserRole).ToListAsync();
            return View(users);
        }
        public IActionResult Creat()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> PostCreat(User user, IFormFile? ImageFile)
        {
            if (ImageFile != null)
            {
                string fileName = $"{Guid.NewGuid()}{Path.GetExtension(ImageFile.FileName)}";
                string folderPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Images/UserImages");
                string filePath = Path.Combine(folderPath, fileName);
                Directory.CreateDirectory(folderPath);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await ImageFile.CopyToAsync(stream);
                }
                user.Photo = fileName;
            }
            user.CreateDate = DateTime.Now;
            user.Password = user.Password?.HashPassword();
            await _context.Users.AddAsync(user);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            var userRoleName = (UserRole)user.UserRole;
            ViewData["UserRoleName"] = userRoleName;
            return View(user);
        }
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }
        [HttpPost]
        public async Task<IActionResult> PostEdit(User postUser, IFormFile? ImageFile)
        {
            var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == postUser.Id);
            if (user == null)
            {
                return NotFound();
            }
            if (ImageFile != null)
            {
                string fileName = $"{Guid.NewGuid()}{Path.GetExtension(ImageFile.FileName)}";
                string folderPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Images/UserImages");
                string filePath = Path.Combine(folderPath, fileName);
                Directory.CreateDirectory(folderPath);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await ImageFile.CopyToAsync(stream);
                }
                user.Photo = fileName;
            }
            user.FirstName = postUser.FirstName;
            user.LastName = postUser.LastName;
            user.Email = postUser.Email;
            user.Phone = postUser.Phone;
            user.UserRole = postUser.UserRole;
            _context.Users.Update(user);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

PowerBlog.Site/Areas/Admin/Views/UserManager/Creat.cshtml
@model User
<div class="row gx-3">
    <div class="col-sm-12">
        <div class="card mb-3">
            <div class="card-header">
                <h5 class="card-title">ثبت کاربر جدید</h5>
            </div>
            <form method="post" enctype="multipart/form-data" asp-action="PostCreat" asp-controller="UserManager" asp-area="Admin">
                <div class="card-body">
                    <!-- Row starts -->
                    <div class="row gx-3">
                        <div class="col-lg-3 col-sm-4 col-12">
                            <div class="mb-3">
                                <label class="form-label" asp-for="@Model.FirstName">نام</label>
                                <input type="text" class="form-control" asp-for="@Model.FirstName" placeholder="نام کاربر را وارد کنید" required>
                            </div>
                        </div>
                        <div class="col-lg-3 col-sm-4 col-12">
                            <div class="mb-3">
                                <label class="form-label" asp-for="@Model.LastName">نام خانوادگی</label>
                                <input type="text" class="form-control" asp-for="@Model.LastName" placeholder="نام خانوادگی کاربر را وارد کنید" required>
                            </div>
                        </div>
                        <div class="col-lg-3 col-sm-4 col-12">
                            <div class="mb-3">
                                <label class="form-label" asp-for="@Model.Email">ایمیل</label>
                                <input type="email" class="form-control" asp-for="@Model.Email" placeholder="ایمیل کاربر را وارد کنید" required>
                            </div>
                        </div>
                        <div class="col-lg-3 col-sm-4 col-12">
                            <div class="mb-3">
                                <label class="form-label" asp-for="@Model.Phone">شماره تلفن</label>
                                <input type="text" class="form-control" asp-for="@Model.Phone" placeholder="شماره تلفن کاربر را وارد کنید" required>
                            </div>
                        </div>
                        <div class="col-lg-3 col-sm-4 col-12">
                            <div class="mb-3">
                                <label class="form-label" asp-for="@Model.UserName">نام کاربری</label>
                                <input type="text" class="form-control" asp-for="@Model.UserName" placeholder="نام کاربری کاربر را وارد کنید" required>
                            </div>
                        </div>
                        <div class="col-lg-3 col-sm-4 col-12">
                            <div class="mb-3">
                                <label class="form-label" asp-for="@Model.Password">رمز عبور</label>
                                <input type="text" class="form-control" asp-for="@Model.Password" placeholder="رمز عبور کاربر را وارد کنید" required>
                            </div>
                        </div>
                        <div class="col-lg-3 col-sm-4 col-12">
                            <div class="mb-3">
                                <label asp-for="@Model.UserRole" class="form-label">نقش کاربر را انتخاب کنید</label>
                                <select asp-for="@Model.UserRole" class="form-select" aria-label="Default select example">
                                    <option selected disabled>این منوی انتخابی را باز کنید</option>
                                    @foreach (var item in Enum.GetValues(typeof(UserRole)))
                                    {
                                        <option value="@((int)item)">@item</option>
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="input-group mb-4">
                            <label class="input-group-text" for="ImageFile">بارگذاری عکس کاربر</label>
                            <input accept=".jpg,.png,.jpeg" type="file" class="form-control" id="ImageFile" name="ImageFile">
                        </div>
                    </div>
                    <!-- Row ends -->
                </div>
                <div class="card-footer">
                    <div class="d-flex gap-2 justify-content-end">
                        <button type="reset" class="btn btn-outline-secondary">پاک کردن همه</button>
                        <button type="submit" class="btn btn-primary">ثبت</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

PowerBlog.Site/Areas/Admin/Views/UserManager/Details.cshtml
@model User
<div class="row gx-3">
    <div class="col-sm-12">
        <div class="card mb-3">
            <div class="card-header">
                <h5 class="card-title">مشاهده جزئیات</h5>
            </div>
            <div class="card-body">
                <!-- Row starts -->
                <div class="row gx-3">
                    <div class="col-lg-3 col-sm-4 col-12">
                        <div class="mb-3">
                            <label class="form-label" asp-for="@Model.FirstName">نام</label>
                            <input type="text" class="form-control" asp-for="@Model.FirstName" value="@Model.FirstName" readonly>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-4 col-12">
                        <div class="mb-3">
                            <label class="form-label" asp-for="@Model.LastName">نام خانوادگی</label>
                            <input type="text" class="form-control" asp-for="@Model.LastName" value="@Model.LastName" readonly>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-4 col-12">
                        <div class="mb-3">
                            <label class="form-label" asp-for="@Model.Email">ایمیل</label>
                            <input type="text" class="form-control" asp-for="@Model.Email" value="@Model.Email" readonly>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-4 col-12">
                        <div class="mb-3">
                            <label class="form-label" asp-for="@Model.Phone">شماره تلفن</label>
                            <input type="text" class="form-control" asp-for="@Model.Phone" value="@Model.Phone" readonly>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-4 col-12">
                        <div class="mb-3">
                            <label asp-for="@Model.UserRole" class="form-label">نقش کاربر</label>
                            <select asp-for="@Model.UserRole" class="form-select" aria-label="Default select example" disabled>
                                <option>@ViewData["UserRoleName"]</option>
                            </select>
                        </div>
                    </div>
                    <div class="input-group mb-4">
                        <img src="~/Images/UserImages/@Model.Photo" alt="@($"{Model.FirstName} {Model.LastName}")" />
                    </div>
                </div>
                <!-- Row ends -->
            </div>
            <div class="card-footer">
                <div class="d-flex gap-2 justify-content-end">
                    <a asp-action="Edit" asp-controller="UserManager" asp-area="Admin" asp-route-id="@Model.Id" class="btn btn-outline-info">ویرایش</a>
                </div>
            </div>
        </div>
    </div>
</div>

PowerBlog.Site/Areas/Admin/Views/UserManager/Edit.cshtml
@model User
<div class="row gx-3">
    <div class="col-sm-12">
        <div class="card mb-3">
            <div class="card-header">
                <h5 class="card-title">ویرایش مقاله</h5>
            </div>
            <form method="post" enctype="multipart/form-data" asp-action="PostEdit" asp-controller="UserManager" asp-area="Admin">
                <div class="card-body">
                    <!-- Row starts -->
                    <div class="row gx-3">
                        <div class="col-lg-3 col-sm-4 col-12">
                            <div class="mb-3">
                                <label class="form-label" asp-for="@Model.FirstName">نام</label>
                                <input type="text" class="form-control" asp-for="@Model.FirstName" placeholder="نام کاربر را وارد کنید" required value="@Model.FirstName">
                            </div>
                        </div>
                        <div class="col-lg-3 col-sm-4 col-12">
                            <div class="mb-3">
                                <label class="form-label" asp-for="@Model.LastName">نام خانوادگی</label>
                                <input type="text" class="form-control" asp-for="@Model.LastName" placeholder="نام خانوادگی کاربر را وارد کنید" required value="@Model.LastName">
                            </div>
                        </div>
                        <div class="col-lg-3 col-sm-4 col-12">
                            <div class="mb-3">
                                <label class="form-label" asp-for="@Model.Email">ایمیل</label>
                                <input type="text" class="form-control" asp-for="@Model.Email" placeholder="ایمیل کاربر را وارد کنید" required value="@Model.Email">
                            </div>
                        </div>
                        <div class="col-lg-3 col-sm-4 col-12">
                            <div class="mb-3">
                                <label class="form-label" asp-for="@Model.Phone">شماره تلفن</label>
                                <input type="text" class="form-control" asp-for="@Model.Phone" placeholder="شماره تلفن کاربر را وارد کنید" required value="@Model.Phone">
                            </div>
                        </div>
                        <div class="col-lg-3 col-sm-4 col-12">
                            <div class="mb-3">
                                <label asp-for="@Model.UserRole" class="form-label">نقش کاربر را انتخاب کنید</label>
                                <select asp-for="@Model.UserRole" class="form-select" aria-label="Default select example">
                                    <option selected disabled>این منوی انتخابی را باز کنید</option>
                                    @foreach (var item in Enum.GetValues(typeof(UserRole)))
                                    {
                                        if ((int)item == (int)Model.UserRole)
                                        {
                                            <option value="@((int)item)" selected>@item</option>
                                        }
                                        else
                                        {
                                            <option value="@((int)item)">@item</option>
                                        }
                                    }
                                </select>
                            </div>
                        </div>
                        <div class="input-group mb-4">
                            <img src="~/Images/UserImages/@Model.Photo" alt="@($"{Model.FirstName} {Model.LastName}")" />
                            <label class="input-group-text" for="ImageFile">بارگذاری عکس مقاله</label>
                            <input accept=".jpg,.png,.jpeg" type="file" class="form-control" id="ImageFile" name="ImageFile">
                        </div>
                        <input type="hidden" asp-for="@Model.Id" value="@Model.Id" />
                    </div>
                    <!-- Row ends -->
                </div>
                <div class="card-footer">
                    <div class="d-flex gap-2 justify-content-end">
                        <button type="submit" class="btn btn-primary">ثبت</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

PowerBlog.Site/Areas/Admin/Views/UserManager/Index.cshtml
@model IEnumerable<User>
@{
    int counter = 1;
}
<div class="table-responsive">
    <div class="table-outer">
        <table class="table table-striped m-0">
            <thead>
                <tr>
                    <th>#</th>
                    <th>نام</th>
                    <th>نام خانوادگی</th>
                    <th>شماره تلفن</th>
                    <th>نقش</th>
                    <th>عملیات</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@counter</td>
                        <td>@item.FirstName</td>
                        <td>@item.LastName</td>
                        <td>@item.Phone</td>
                        <td>@item.UserRole</td>
                        <td>
                            <a asp-action="Details" asp-controller="UserManager" asp-area="Admin" asp-route-id="@item.Id" class="btn btn-outline-info">جزئیات</a> <a asp-action="Edit" asp-controller="UserManager" asp-area="Admin" asp-route-id="@item.Id" class="btn btn-outline-warning">ویرایش</a> <a asp-action="Delete" asp-controller="UserManager" asp-area="Admin" asp-route-id="@item.Id" class="btn btn-outline-danger">حذف</a>
                        </td>
                    </tr>
                    counter++;
                }
            </tbody>
        </table>
    </div>
</div>